name: pr_ci_i18n
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**/en-US.json"
  push:
    branches:
      - main
    paths:
      - "**/en-US.json"

jobs:
  i18n_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Execute i18n Key Identifiers Check
        working-directory: ./frontend/i18n/check
        run: python i18n_check_key_identifiers.py

      - name: Execute i18n Unused Keys Check
        if: always()
        working-directory: ./frontend/i18n/check
        run: python i18n_check_unused_keys.py

      - name: Execute i18n Non Source Keys Check
        if: always()
        working-directory: ./frontend/i18n/check
        run: python i18n_check_non_source_keys.py

      - name: Execute i18n Repeat Values Check
        if: always()
        working-directory: ./frontend/i18n/check
        run: python i18n_check_repeat_values.py
